sudo: false
language: node_js
node_js:
  - 13

install:
  - yarn install --frozen-lockfile

script:
  - yarn lint:fix
  - yarn test

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app:
    master: atlas-discord-bot
    staging: atlas-discord-bot-canary
    dev: atlas-discord-bot-preto

notifications:
  email: false


after_success:
  - wget https://raw.githubusercontent.com/Psykka/travis-ci-discord-webhook/master/build.sh
  - chmod +x build.sh
  - ./build.sh success $DISCORD_WEBHOOK

after_failure:
  - wget https://raw.githubusercontent.com/Psykka/travis-ci-discord-webhook/master/build.sh
  - chmod +x build.sh
  - ./build.sh failure $DISCORD_WEBHOOK

after_deploy:
  - wget https://raw.githubusercontent.com/Psykka/travis-ci-discord-webhook/master/deploy.sh
  - chmod +x deploy.sh
  - ./deploy.sh $DISCORD_WEBHOOK