name: CI-CD

on:
  - push
  - pull_request

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install coverge-reporter
        run: curl -L https://coveralls.io/coveralls-linux.tar.gz | tar -xz -C /usr/local/bin

      - name: Install packages
        run: yarn install --immutable

      - name: ESLint
        run: yarn lint

      - name: Unit test
        run: yarn test

      - name: Coveralls report
        run: yarn coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
          COVERALLS_SERVICE_NAME: github-actions
          COVERALLS_SERVICE_JOB_ID: ${{ github.job }}
          COVERALLS_GIT_BRANCH: ${GITHUB_REF##*/}
